### ISSUE TITLE
Ceil of a number in sorted array

### ISSUE THREAD

**Issue by SanskritiKushik5** [SR-Sunny-Raj/Hacktoberfest2021#11]
This is a program of Binary Search. Can I contribute a solution to this problem?

**Comment by SR-Sunny-Raj** [comment]
Hey @SanskritiKushik5  ,This repo is marked as excluded and any contribution made into it will not be considered valid, so please share your solution into this repository [repo link](https://github.com/SR-Sunny-Raj/Hacktoberfest2021-DSA).

**Comment by SanskritiKushik5** [comment]
Thank you!
